### ISSUE TITLE
Space in prompt

### ISSUE THREAD

**Issue by colinmarc** [j0ru/kickoff#119]
Hi, I really like kickoff!

I'm using the following config:

```
prompt = '> '
```

However, the trailing space gets stripped when the prompt is displayed, and it shows as `>foo`. I realize this is extremely minor. :sweat_smile:

**Comment by j0ru** [comment]
Hi Colin,
no worries! 
The problem is not that the space gets stripped, but that the prompt and the query are rendered as different 
text lines and I naively slap them together. If they would share a layout, the correct character spacing between them would be computed, but like this it looks like the space isn't even rendered. Adding a bit of default spacing seems reasonable b980cc3
