### ISSUE TITLE
Window manager compatibility

### ISSUE THREAD

**Issue by tpoliaw** [j0ru/kickoff#4]
Was interested in trying this as an alternative to rofi, but can't get it to run. I'm using i3 and it's giving
```
thread 'main' panicked at 'Initial roundtrip failed!: NoCompositorListening', src/main.rs:83:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is this intended to work or does it require a compositing window manager to be available?

**Comment by j0ru** [comment]
Unfortunately it is not possible to use kickoff with a non wlroots compositor, wlroots beeing the wayland compostior maintained by the Sway project or to be more precise the wlr wayland protocol extensions that they defined. There also will be no X support in the future since there are already many other program launchers that work very well and the sole focus of kickoff is to work well with wayland.

That beeing said, I will improve the error message to hint at possible reasons for this failure.
If you liked the look of kickoff in the screenshot, you can try my old [rofi config](https://github.com/j0ru/dotfiles/blob/master/.config/rofi/config) which was the inspiration for the layout of kickoff.
