### ISSUE TITLE
Delete key inserts missing unicode character

### ISSUE THREAD

**Issue by edward-shen** [j0ru/kickoff#5]
Hello! Thanks for your launcher; currently testing it out as a daily driver.

I've found that pressing the delete key inserts a unicode character instead of properly handling the delete key, whether it be do nothing or function identically to the backspace key.

Unfortunately I'm not able to show you a screenshot (as losing focus closes the launcher), but it should be reproducible on a fresh build.

Version: 0.4.5

**Comment by j0ru** [comment]
Hey, thanks for trying it!
Kan you tell me what keyboard layout you use?

**Comment by edward-shen** [comment]
Just the standard US QWERTY layout.

**Comment by j0ru** [comment]
Ah, just noticed that I misread your message.
Usually the delete key would remove the letter right of the cursor, but since a cursor is not implemented I didn't handle the delete key and it got interpreted as a letter. I think the most intuitive thing would be to set it to the same behavior as the backspace key

**Comment by j0ru** [comment]
Could you try out the newest commit to validate that your issue is solved?

**Comment by edward-shen** [comment]
Yeah, looks like it's fixed in the newest version. Thanks!

Also dang the perf difference between debug and release mode is insane!

**Comment by j0ru** [comment]
Yes, while programming  I was really worried till I compiled it for the first time in release mode ^^
Thanks for testing!
