### ISSUE TITLE
kickoff --from-stdin doesn't do anything

### ISSUE THREAD

**Issue by Relwi** [j0ru/kickoff#71]
I'm trying to run this `kickoff --from-stdin` in the terminal but the app get stuck and does nothing. I need to configure something first? Don't know how I can get the logs.

**Comment by j0ru** [comment]
The purpose of `--from-stdin` is to read a list of programs from stdin. Something like this:
`echo "foobar=firefox" | kickoff --from-stdin`
This will display kickoff with the single option, that launches firefox.

Due to an architectural limitation the input stream has to be closed before kickoff can display, which is the reason why nothing happens when you just launch it without providing an input

**Comment by Relwi** [comment]
Oh okay, I understand, thanks!

**Comment by j0ru** [comment]
No problem :)
