### ISSUE TITLE
applications not starting in terminal

### ISSUE THREAD

**Issue by ThomasFoernzler** [j0ru/kickoff#9]
Sry upfront if this issue is not caused by your menu.

When i try to start for example networkmanager or btop with kickoff, it doesnt open a terminal with the app but instead nothing happens.
When my sway crashes(unrelated), i see some output of the application in the tty (in case of networkmanager, there are some distorted blue lines in between the sway errors).
So it seems, the application does start, but in the tty, unusable to me when sway is running.
Do i need to specify a default terminal somewhere or is this caused by sway or not intended to work by you?

Thanks for kickoff, looks nice and does what i should (most of the times ;))

**Comment by j0ru** [comment]
Hey,

thanks for your feedback! Unlike something like the gnome launcher, kickoff currently only works with a list of binaries in your path. The gnome launcher uses .desktop files that describe what a program is, it's name and icon and how it should be started (i.E. in a terminal). With a list of of binaries in your path, you don't have that luxury. Kickoff only sees a list of executable files and lists them. Since kickoff is owned by the wm and started programs are forked from it, all started programs are also owned by the wm, which is why you see their output after sway crashes.

To fix this kickoff would need support for desktop files and there is already a request for that #3
I already started working on it in autumn, but the problem is a bit more complex than I was anticipating and university kept me busy since then, but I should have some time soon™ to get back working on it.

 Cheers,
joru
