### ISSUE TITLE
Is there a way to search with non-ascii characters as well?

### ISSUE THREAD

**Issue by blnvdanil** [j0ru/kickoff#92]
Helllo! Thanks for this awesome tool :)
I just was wondering if there is a way to search with non-ascii characters. I am using two beyboard layouts, and sometimes when I am searching with non-english layout, characters are just being skipped.

I think that the best behaviour is to map non-ascii charaters to ascii characters, depending on a keyboard layout. Is it possible to implement this kind of mapping from others layouts to english layout?

I am not sure if my suggestion is the only way to solve my problem

**Comment by j0ru** [comment]
Heya,
I'm surprised I never noticed that, having some non-ascii characters on my keyboard as well, but I guess most programs restrict their name to ascii only.
Displaying the characters works, the error seems to be in the input code. I'll have a look at it, thanks for reporting!

**Comment by blnvdanil** [comment]
@j0ru 
Thanks for a quick reply!
Actually I ment not only being able to type non-ascii characters, I mean for example if I type "икфму" on non-ascii layout, that would be cool if the program will search for "brave" as well, because "brave" is what I got if type with english layout, I am not sure about defficulties of implementation btw

**Comment by j0ru** [comment]
Ah, ic
Trying to interpret the same input with different layouts could be difficult, since that opens up a cluster of problems (keyboard types vs. layouts). Searching for multiple keywords at once could be easy, but I'll have to investigate that.

Till then, maybe [this](https://github.com/artemsen/swaykbdd) could help your problem. Haven't used it myself, so I can't say if it fits the use-case exactly.

**Comment by j0ru** [comment]
Unfortunately I won't implement this, for me the complexity outweighs the problem :/
PRs are welcome, but until then I'll close the issue
